### ISSUE TITLE
[1.12.2] BetterChests ignore custom config values from cfg file

### ISSUE THREAD

**Issue by CplPibald** [Aroma1997/BetterChests#100]
If you change the config in 1.12.2, (eg: energy cost) the mod always uses the default values in game.

It also always uses the "ADD" key as the backpack key.  You can change it from the controls menu (and the new value is saved to options.txt) but when you close and re-launch Minecraft, it is set to ADD again.

**Comment by Aroma1997** [comment]
This is fixed in build 74, but please create two separate issues for two separate bugs next time.

**Comment by Aroma1997** [comment]
No worries.
