### ISSUE TITLE
Void upgrade deletes itself

### ISSUE THREAD

**Issue by iamtpage** [Aroma1997/BetterChests#104]
Currently running Aroma1997core-1.12.2-2.0.0.0.b135 and BetterChests-1.12.2-2.1.1.3
Minecraft 1.12.2

Hi,

- If I place a Void upgrade in a chest upgrade GUI, it deletes itself.
- If I place a Void upgrade and a blacklist filter inside a chest upgrade GUI at the same time, the void upgrade deletes both
- If I place a blacklist filter, close the chest upgrade GUI, and then place a void upgrade in the chest upgrade GUI. The void upgrade won't delete the blacklist filter and itself. ~~~It will delete everything (as expected) except for enchanted items in the chest inventory.~~~
- If I modify the blacklist filter to compare NBT data and damage, the void upgrade deletes itself and the blacklist filter.

Would it be possible to modify the void upgrade to ~~~delete enchanted items, as well as~~~ not affect the upgrade GUI portion of the chest?

**Comment by Aroma1997** [comment]
I think I know what's going on. I'll fix it once I'm home.

**Comment by Aroma1997** [comment]
Should be fixed in build 75
