### ISSUE TITLE
Backpack hotkey disconnects from world

### ISSUE THREAD

**Issue by Stanyard** [Aroma1997/BetterChests#107]
Pressing ADD to open the backpack in my inventory boots me from my singleplayer world.
[latest.log](https://github.com/Aroma1997/BetterChests/files/1814478/latest.log)

Java 1.8.0_25
Minecraft 1.12.2
Forge 14.23.2.2627
Better Chests 3.0.0.0.b82
Aroma1997Core 2.0.0.0.b147

Tested in fresh superflat world with no other mods.

**Comment by Aroma1997** [comment]
This should be fixed in build 148 of Aroma1997Core. If it still doesn't work, please let me know.
