### ISSUE TITLE
[Bug]: Minor Graphical Issue

### ISSUE THREAD

**Issue by Akitori** [Aroma1997/BetterChests#109]
Heya. There's a small bug at the moment render wise. If you have a better backpack in your inventory, it renders the backpack, correct?

There is some slightly `lag` if i were to call it that, on the backpack. Not really noticeable if you glance at it,

Reason i point that out is due to a small bug involving Elytra. If you glide using a elytra, the backpack floats in the air.

1. Get elytra with backpack in inventory.
2. Fly.
3. Enjoy floating backpack.

**Comment by Aroma1997** [comment]
This is more complicated than one could think. I'll put it on my todo-list, but no eta.
