### ISSUE TITLE
Mignt have a bug ?

### ISSUE THREAD

**Issue by wolfdarkstar** [Aroma1997/BetterChests#110]
Hi first thanks for keeping the mod up to date .
I have tried to open the backpack with the key bind and it shutdown with this note ( **A fatal error has occurred , This connection is terminated** ) 
I have tried to do a test with only the core & BC only but I get the same results .
I still can get the bag to open with out using key bind . 
This dos not to the best of my knowledge produce a crash log at least none that I can see .
I am running version 
mincraft 1.12.2 latest 
Forge 14.23.4.2703
Java1.8.0.171

One more thing I am using JEI and unless it has been removed from the pack can't make the BC book ..
Please if you have time look in to this ..

Thanks for your time Have A Nice Day  :-)

**Comment by Aroma1997** [comment]
Can you send me a log file (.minecraft/logs/fml-client-latest.log) of the bug happening?

**Comment by wolfdarkstar** [comment]
Thanks jest sent it hope it gets to you if not please resend request ( the email I sent was to large I went over the limit for the email )

**Comment by Aroma1997** [comment]
I didn't receive anything. Can you pastebin/ist the log file?

**Comment by wolfdarkstar** [comment]
OK I hope this is what you need sorry for the mess I tried to send you 2 files before & it was to much for the mail to handle .
Thanks for the fast response .

Have A Nice Day :-)
________________________________

**Comment by wolfdarkstar** [comment]
[fml-client-latest.log](https://github.com/Aroma1997/BetterChests/files/2051944/fml-client-latest.log)

I give up Hear is the log I hope

**Comment by Aroma1997** [comment]
Are you playing on a dedicated server?

**Comment by wolfdarkstar** [comment]
no it is by my self on my PC running win 10 .

Have A Nice Day :-)
________________________________

**Comment by Aroma1997** [comment]
I could not find anything indicating there is something going wrong in the log file.
Seeing that this is a 1.7.10 issue though, I sadly have to say that the 1.7.10 version of BetterChests is no longer supported, so a fix for your issue is not likely to come. However the mod is open source, so if you want to fix it yourself, feel free to go ahead.

**Comment by wolfdarkstar** [comment]
sorry to say this is not a 1.7.10.mod but a 1.12.2. mod ( according to the tag )

OK I re did the crash on my test world I only have the CB & the core mods installed I will put up the logs to the hub .
the last ones might have been the wrong ones . hope this helps ..

PS . what about no book  in 1.12.2 ? will this be addressed in a further update ? .

Have A Nice Day :-)
________________________________

**Comment by wolfdarkstar** [comment]
[debug.log](https://github.com/Aroma1997/BetterChests/files/2066153/debug.log)
[latest.log](https://github.com/Aroma1997/BetterChests/files/2066154/latest.log)

**Comment by Aroma1997** [comment]
Ah, I didn't know this was a 1.12 issue since the first log file you sent indicated a 1.7.10 instance.
This bug is already fixed in the AromaCore build 148 and newer (you're using build 147)

**Comment by wolfdarkstar** [comment]
Thanks & stay safe

Have A Nice Day :-)
________________________________
