### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by mihartsy** [Aroma1997/BetterChests#111]
Minecraft 1.12.2 
BetterChests-1.12.2-3.0.0.0.b8

Game immediately crashes as soon as you press play.

[crash-2018-06-12_20.07.01-client.txt](https://github.com/Aroma1997/BetterChests/files/2093921/crash-2018-06-12_20.07.01-client.txt)

Thank youu

**Comment by Aroma1997** [comment]
You need to use the latest version of AromaCore and it'll work.
