### ISSUE TITLE
Backpack issues

### ISSUE THREAD

**Issue by Dezail** [Aroma1997/BetterChests#112]
I'm play in the FTB Horizons mod pack version 2.1.1 and I'm having issues with the adjustable backpack not taking upgrades.  I place both the back pack and the storage upgrade in the crafting grid and nothing shows as an output. I've tried it in the tinkers crafting table, mine craft table and player table with no luck.

**Comment by Aroma1997** [comment]
Seeing you closed this issue, I assume you managed to make it work.
