### ISSUE TITLE
I'm confused what the water upgrade does for 1.12.2

### ISSUE THREAD

**Issue by DeathByTrystan** [Aroma1997/BetterChests#114]
![2022-11-03_16 30 48](https://user-images.githubusercontent.com/41507636/199854362-71c5ba25-fdaa-4ca6-8ddc-4ddeb74bd4b4.png)

**Comment by Aroma1997** [comment]
It works like an infinite water source.
In a tank, if collects more water, if at least two buckets of water are present.
In a chest, it fills empty fluid containers, if at least two buckets worth of water in fluid containers are contained in the chest.
