### ISSUE TITLE
Unbreaking Upgrade Duping Glitch

### ISSUE THREAD

**Issue by AshtonFearBolt** [Aroma1997/BetterChests#16]
I went into singleplayer, put a unbreaking upgrade on a chest, used tnt to blow it up, and the chest remained but the adjustable chest item was dropped, henceforth duping the chest

**Comment by PeKlim** [comment]
Here is my mod spotlight in czech languague, but you can see this bug here from 50:43. Version is 1.1.1.5 for 1.7.10 - https://www.youtube.com/watch?v=XYCwOkkzxzg
