### ISSUE TITLE
Better Chest feeding Upgrade

### ISSUE THREAD

**Issue by Xyrys** [Aroma1997/BetterChests#54]
Hi,

Just thought I would mention this, since I cannot find any other mention on google.

Animal feeding upgrade won't feed on any version past 1.1.1.5.

Tested versions 1.1.1.4, 1.1.1.5, 1.1.1.6, 1.1.1.7, and 1.1.1.8.

1.1.1.4 and 1.1.1.5 work fine.

Tried SMP, SSP, only mods loaded, and added to DW20 1.7.10 pack.

Xy.

**Comment by lwshll1** [comment]
yes i was checking to see if u r still planing on backport this to 1.7.10 as of today it's still not working. only reason im asking is trying to not use MFR as much as i can

**Comment by Aroma1997** [comment]
The thing is: making a backport requires a lot of work. Therefore I won't do one untill someone finds a game-breaking bug.
