### ISSUE TITLE
Lightweight Upgrade Enhancements (Particle Effects and 1 Block Step Up)

### ISSUE THREAD

**Issue by Mochnant** [Aroma1997/BetterChests#56]
As an enhancement suggestion, it would be nice to remove the Speed particle effect (and even the status icon if possible!) from the lightweight bag enhancement.  I personally find it rather distracting from this otherwise great enhancement.

I would also suggest lightweight act like Thaumcraft's Boots of the Traveller and allows you to step up 1 block when moving.  This would make long distance travel very useful.

Thank you!

**Comment by Aroma1997** [comment]
This is somewhat fixed in the 1.12 version, since the lightweight upgrade is gone.
