### ISSUE TITLE
Applied Energistics Storage Cells in Adjustable Chest cause disconnect

### ISSUE THREAD

**Issue by SirWilli** [Aroma1997/BetterChests#59]
hey,

if you put some me storage cells in to a adjustable chest you get kicked with the errer ```Internal Exception: io.netty.handler.codec.Decoderexception: java.io.IOException: Packet was larger than I expected, found 33522 bytes extra whilst reading packet 53```
in multiplayer.

**Comment by SirWilli** [comment]
Why wontfix?

**Comment by Aroma1997** [comment]
Because this is something I can't do anything about.
It is basically if the packet of the item being synced is bigger than 4MB, it will screw up, the only thing I could do about this is make it not accept AE drives. It's not meant to have them anyways.

**Comment by SirWilli** [comment]
Okay.
