### ISSUE TITLE
Planter upgrade ignoring meta data of seeds?

### ISSUE THREAD

**Issue by yanbloke** [Aroma1997/BetterChests#60]
When I place Natura's Cotton seeds (xxxx:1) in the chest, it plants Barley (xxxx)

**Comment by Mochnant** [comment]
I can confirm that this happens for me as well.  Cotton seeds plant as barley.

**Comment by Aroma1997** [comment]
What version?
Log.

**Comment by Mochnant** [comment]
Not sure what log you're looking for.

I was using Crackpack 2.0.1.0 which has Better Chests v1.1.1.5.  Crackpack has recently updated to v1.1.1.8 and I have not tested this issue there.

**Comment by Aroma1997** [comment]
in the .minecraft/logs/ directory

**Comment by Mochnant** [comment]
I changed over to harvesters/planters, so I am not sure I would have any useful logs anymore.  I'll check tonight, but perhaps @yanbloke does?
