### ISSUE TITLE
Tree chopper/planter upgrade

### ISSUE THREAD

**Issue by vinixd1997** [Aroma1997/BetterChests#61]
could you make an upgrade that can chop down trees? That would be really nice, and that the planter uprgade can plant saplings....

**Comment by GruNoof** [comment]
Hello Aroma,

+1 this request. I'm working on a minimalist mod pack for an upcoming YouTube Let's Play series with my daughters, and it would greatly simplify the setup. Thanks for your consideration.

**Comment by Gunner76th** [comment]
+1 for seeing this upgrade added to the 1.8 release of the mod.

**Comment by Aroma1997** [comment]
That's a new feature in the 1.12 version of the mod.
