### ISSUE TITLE
Crash when using InventoryTweaks commands?

### ISSUE THREAD

**Issue by Emanresu13** [Aroma1997/BetterChests#62]
I use CTRL+SHIFT+Click or SPACE+Click, and it moves the items in the chests somewhere else in the chest, and then if I do it a second time, the game freezes and crashes? How do I fix this, or will I just have to use another chest? Also all the chests are max slot upgraded and have the unbreakable upgrade on it, nothing else.

**Comment by Aroma1997** [comment]
Log would be helpful

**Comment by Emanresu13** [comment]
It doesn't create a log, just freezes till windows gives me an option to end the process

**Comment by Aroma1997** [comment]
Log would be helpful (.minecraft/log)

**Comment by Emanresu13** [comment]
https://www.dropbox.com/s/gbxqqa2iwv59d06/2015-01-13-1.log.gz?dl=0
Sorry, I misunderstood what you where talking about. Also my Aroma Core version is 1.7.10-1.0.2.13,
BetterChests version is 1.7.10-1.1.1.8, and Inventory Tweaks is 1.59-DEV-156. The Core and InvTweaks is default in the modpack, and I manually added BetterChests via Minecraft Forum Link.

**Comment by EverSeeking** [comment]
I'm having the same issue http://puu.sh/eChg7/76872eb4e3.jpg

Any of the inventory tweaks combo controls to move all items, or all items of a specific type freezes up my client - no crash.

Also, I'm looking for relevant logs for you as well, but the forge logs don't appear to be any help, and I don't see any others in my pack's instance folder.

* Crackpack 2.0.3.0
 * Aroma CCore 1.7.10 - 1.0.2.13
 * Better Chests 1.7.10 - 1.1.1.8
 * Inventory Tweaks 1.59-DEV-156

**Comment by Aroma1997** [comment]
I have an idea.

**Comment by Emanresu13** [comment]
What is it?

**Comment by amezick** [comment]
I have the same issue playing the Clouds of Darkness FTB modpack.

**Comment by Gunner76th** [comment]
Do we have any update on this bug, and or if/when it will be fixed for either 1.7.10 or 1.8?

**Comment by Aroma1997** [comment]
I currently have other things to do and I'm not sure when and if I continue updating BetterChests. Therefore I don't know when this will get fixed.

**Comment by Aroma1997** [comment]
This is most likely fixed in the 1.12 versiuon of BetterChests. The old versions are discontinued, so it won't get fixed there.
