### ISSUE TITLE
Adjustable Bag is missing texture (1.8.1)

### ISSUE THREAD

**Issue by L0neGamer** [Aroma1997/BetterChests#63]
![2015-01-16_21 18 27](https://cloud.githubusercontent.com/assets/10566848/5784621/bd8ac5a8-9dc5-11e4-8ee0-5f859df85164.png)

As can be seen above, the adjustable bag is missing a texture, while all the other items in the BetterChests seem to render properly.

I also noticed in the log that there was a lot of spamming about missing files: http://pastebin.com/FVxTWCRx

Please could you look into this?

![2015-01-16_21 24 57](https://cloud.githubusercontent.com/assets/10566848/5784658/283140a8-9dc6-11e4-9a32-fe264c053e6a.png)
This is what my mods folder looks like.

**Comment by Aroma1997** [comment]
I can't do anything about that untill Forge implements something like IItemRender again.

**Comment by ProRedHD** [comment]
Couldn't you just use the vanilla model json format for the model of the backpack?

**Comment by ProRedHD** [comment]
It worked! I made a model for the backpack! All made with the new custom rendering system of minecraft 1.8 :P 
![2015-05-03_19 13 40](https://cloud.githubusercontent.com/assets/11902258/7446009/7d711140-f1c9-11e4-82be-bf3107bac4f6.png)

**Comment by Aroma1997** [comment]
I'm really busy at the moment, but when I can work on things again, I will reimplement the old bag rendering, but thanks anyways...

**Comment by Gunner76th** [comment]
@ProRedHD could you possibly send me the files needed for your rendering of the backpack? As of yet this issue has yet to be addressed.

**Comment by ProRedHD** [comment]
@Gunner76th Sorry, I think I deleted the file :(

**Comment by Gunner76th** [comment]
As I myself and trying to learn how to write minecraft mods, I guess what better way than to learn how to do the artwork lol. So I guess my next question is, so you remember or know where the artwork needs to be located, and how do I find out what file name it needs to have in order for the mod to use it? I am thinking it goes in the assets folder within the .jar file, but I want ask someone who knows for sure before I go mucking around with things.

**Comment by Gunner76th** [comment]
In looking at the files themselves, I noticed that there is already a texture file for the bag, however in the models folder and subfolders, there is no json file for the bag, but there is for the chest and everything else.

**Comment by ProRedHD** [comment]
You need to put the models file into the models/item file. I do not know how to render specific parts of the models when needed.

**Comment by Aroma1997** [comment]
Added a placeholder texture in the last commit.
