### ISSUE TITLE
Player Feeding upgrade bug 1

### ISSUE THREAD

**Issue by KnatteAnka** [Aroma1997/BetterChests#64]
if you place one bread in the bag and get hit to lower the hunger it can feeds as intended. (bread = 0 but not empty slot!)
But if more hungry it can continue feeding and give you hunger;) and lower the food count to negative.

found on multiplayer

**Comment by Aroma1997** [comment]
What version?
Also log would be helpful.

**Comment by KnatteAnka** [comment]
Versions: liteloader-installer-1.8.0-00-SNAPSHOT, forge-1.8-11.14.0.1290-1.8-installer, BetterChests-1.8-1.1.2.0
Log: http://pastebin.com/LJUejKkG
recreated it also on singelplayer

how to replicate it:
get a bag
add player feeding upgrade
insert 1 bread
get hurt and look at the amount of breads left after each time the bag eats
