### ISSUE TITLE
Player Feeding Bag will use Rotten Flesh

### ISSUE THREAD

**Issue by Mochnant** [Aroma1997/BetterChests#65]
The Player Feeding upgrade to the Bag will feed Rotten Flesh to the player if it appears before valid food in the inventory.  The bag should not feed Rotten Flesh if there is better (non-poisonous) food in the bag, but preferably it should not feed it at all.

**Comment by Mochnant** [comment]
On a technical note, it may be possible to use getPotionEffect on the food item to see if it has the Hunger debuff and skip it, if so.  I believe that is how Rotten Flesh works.

**Comment by Aroma1997** [comment]
You should be able to solve that issue with the filter upgrade.

**Comment by Mochnant** [comment]
That might be a workaround (thanks), but that is not a true fix.  I can think of no scenario where feeding a player poisonous food automatically would be something desirable.

**Comment by Aroma1997** [comment]
Well, mods give you features and challenges. In my opinion it would be kinda cheaty if this would be directly in the mod.

**Comment by Mochnant** [comment]
That's interesting!  I think I'd consider most of the BetterChests mods kinda cheaty.  Almost everything is too cheap, too easy to make, and too convenient.  Why build an advanced farm when a chest will do it for no power and very few resources?  Why make a powered furnace when a chest will do it for no power?  Why maybe a diamond chest when a better chest can be upgraded to 96 slots for practically no resources?  And then there are the bags, of course, which are essentially near-limitless personal storage.

That said, it is fun, and easy-mode, and some people like that (not saying I don't!).  I know this isn't the place for a deep discussion, but I thought it odd that you think the filtering of poisonous edibles from the Player Feeding upgrade is cheaty, but the rest is not.  Thanks for listening.

**Comment by Aroma1997** [comment]
I don't say the rest isn't cheaty.
I'm currently implementing fuel cost for the people who say it is too cheaty.
