### ISSUE TITLE
InfiniteInvo Bug

### ISSUE THREAD

**Issue by yosomith** [Aroma1997/BetterChests#66]
There is a bug with this mod and InfiniteInvo where opening a Better Chest does weird things with your inventory, it seems like it dupes but it doesn't, it's just a display bug but it does make using the two mods together very difficult.

This was using the latest version of both InfiniteInvo (1.0.25) and BetterChests (1.1.1.8)

**Comment by Aroma1997** [comment]
Log.

**Comment by yosomith** [comment]
Here is the forge log. https://www.dropbox.com/s/4atkunva6mlaovz/fml-client-latest.log?dl=0

If needed here is my inventory before opening the chest: http://i.imgur.com/AETHbRT.png

Here is the chest open: http://i.imgur.com/rdXQaKg.png

And last the result afterwards: http://i.imgur.com/zdTeptR.png

Picking up any item reverts the inventory back to the first pic so no items are lost or duplicated.

**Comment by Aroma1997** [comment]
Yup,
https://github.com/Funwayguy/InfiniteInvo/issues/6
that is a better place to report it. It is his bug. (I think)

**Comment by yosomith** [comment]
I wasn't sure who to report it to so I thought both of you would be better.

**Comment by Funwayguy** [comment]
Yea it looks more like my side @Aroma1997 sorry for the inconvenience.

**Comment by Aroma1997** [comment]
No probs.
