### ISSUE TITLE
Breaking/Placing Upgrade

### ISSUE THREAD

**Issue by KnatteAnka** [Aroma1997/BetterChests#67]
A Breaking upgrade that use energy upgrade to break the block behind it using tool inside and applying the tools enchentment.
This way you can do farm if a item is transported to the chest and there broken down.
like for a tree farm or a manual cobblestone or other farm that you transport the item to the chest.

A Placing Upgrade place the item inside behind it if it is air or water behind it 
This can be used to plant tree seeds. or other item that need to be placed.

**Comment by Aroma1997** [comment]
That's a new feature in the rewrite.
