### ISSUE TITLE
[1.8-1.2.0.0] Can't upgrade chests with right click

### ISSUE THREAD

**Issue by kreezxil** [Aroma1997/BetterChests#71]
With "slot upgrade" in hand, right clicking a wooden chests no longer upgrades it to a better chest.

**Comment by kreezxil** [comment]
However, if you manually craft a better chest, you can then apply the "slot upgrade" with right click.

**Comment by Aroma1997** [comment]
It never did.
To Upgrade a wooden Chest to an Adjustable Chest, use the BetterChests Upgrade.

**Comment by kreezxil** [comment]
That's what I used, and that's what I thought I had described.

**Comment by kreezxil** [comment]
Oops. I see what you mean.

**Comment by Aroma1997** [comment]
So... everything works?

**Comment by kreezxil** [comment]
yeah, everything is fine. I had a senior moment. :)
