### ISSUE TITLE
Error with BetterChests1.2.0.0

### ISSUE THREAD

**Issue by DatrixTSW** [Aroma1997/BetterChests#72]
I seem to just CTD before i reach the Minecraft welcome (Version 1.8) screen I am only using Aroma1997Core 1.0.3.4 AromaBackup 0.0.1.0 and Better Chests 1.2.0.0 Latest version of Forge so far is 11.14.1.1309 right now and I use McPatcher 5.0.0_02
Crash Log: http://pastebin.com/NiSv6LgP
FML Log: http://pastebin.com/UJCAMq4v

**Comment by Aroma1997** [comment]
Fixed in new version of core. Get the pre-release from http://files.aroma1997.org/mcmods/testing/
