### ISSUE TITLE
1.7.10-1.1.1.8 Feeders and filters

### ISSUE THREAD

**Issue by Tergiver** [Aroma1997/BetterChests#74]
Setup: One Chest with energy upgrade and 7 slot upgrades. 7x7 wall around chest. Several stacks of wheat in the chest.

Spawn two cows.

It does not feed them.

Add a whitelist filter (empty). It now feeds them.

This is backwards, but if I add wheat to the filter, it doesn't feed them.

What I want is to also add a kill upgrade and collectors, but the collectors don't pick up with the whitelist unless I add beef/leather to the filter. That is correct behavior on the part of the collectors. The problem is the feeder. It only feeds if there is an empty whitelist filter.

To make it work, I added the feeder, then an empty whitelist, then the kill, collect, and another whitelist with beef/leather. Is it supposed to work this way?

**Comment by Aroma1997** [comment]
Looks like I forgot to add a "!" somewhere to invert the logic.

**Comment by Aroma1997** [comment]
Works for me.
