### ISSUE TITLE
cant "downgrade" bag in 1.1.0.3

### ISSUE THREAD

**Issue by shadoxxhd** [Aroma1997/BetterChests#75]
i have the better chest hammer in my inv, but on shft-rightclick with the bad it opens the regular inventory instead of the upgrade ones (want to remove resupply upgrade, its really annoying if you go mining with cobble in the bag)

**Comment by JustKayneNL** [comment]
do you have an aromic hammer on you?

**Comment by shadoxxhd** [comment]
yes, doesnt help no matter if in inventory, in bag, in hotbar, directly
adjacent to bag, ...

**Comment by Aroma1997** [comment]
So you have an aromic hammer in your inventory and you shift-right-click the bag, but it shows the inventory?
Can you give me a log of when you do that?

**Comment by shadoxxhd** [comment]
atm i dont have that minecraft installation ready to use, ill look into it
soon

**Comment by Aroma1997** [comment]
Could not reproduce
