### ISSUE TITLE
Mining dimension causing NEI to go away.

### ISSUE THREAD

**Issue by Aulton** [Aroma1997/BetterChests#76]
Exactly as the title suggests. In my pack, as soon as I go through the mining portal, I lose my NEI until I reinstall the pack (getting it from FTB.)  Also note that hitting O doesn't do anything at all.
Using version 1.1.0.1 for Aroma1997 Mining Dimension 1.0.4.83 for NEI. (I couldn't find a github for the dimension mod, so I figured I'd post it here.)

**Comment by Aroma1997** [comment]
Wrong mod. Report here: http://code.aroma1997.org/aroma1997core/issues
