### ISSUE TITLE
Calling rotate in 1.8 causes the chest to lose contents and upgrades

### ISSUE THREAD

**Issue by Vanhal** [Aroma1997/BetterChests#77]
I've added a wrench to Progressive Automation that can rotate blocks but I got a bug report that said that when they used it your chest lost all their contents and any upgrades that were on them.

Bug report here: https://github.com/Vanhal/ProgressiveAutomation/issues/117

**Comment by Aroma1997** [comment]
This is probably fixed in the 1.12 version of BetterChests. The old version is discontinued though.
