### ISSUE TITLE
backpack is lost

### ISSUE THREAD

**Issue by roxieraven327** [Aroma1997/BetterChests#80]
i use the keepInventory rule on all my worlds but when i die and i have your backpack in my inventory i lose it like completely like it was never there to begin with. i use the:
recommended forge of 10.13.2.1291
minecraft version 1.7.10
heavily modded (too many to list here but will if you want/need them)
betterchests mod version 1.1.1.9
aroma core 1.0.2.13

i hope this can be fixed as i prefer your backpack to use to feed me and stuff. thank you for your time!

**Comment by Aroma1997** [comment]
The 1.7.10 version is discontinued, but if this happens on the 1.12 version as well, please let me know.
