### ISSUE TITLE
Sugar cane not being harvested

### ISSUE THREAD

**Issue by Gunner76th** [Aroma1997/BetterChests#83]
Is it possible to add sugar cane to the list of crops that the harvester upgrade collects? Perhaps set it to always leave the bottom sugar cane in place similar to how the killing upgrade + ai always leaves 2 passive mobs?

**Comment by Aroma1997** [comment]
The Harvester Upgrade already harvests Sugar Cane.

**Comment by Gunner76th** [comment]
Interesting, if this is the case, it is not working in 1.8. I have a chest with the harvest upgrade, with 4 sugar canes around it on the cardinals, and then potatoes out past that to range. the only item it is harvesting is the potatoes.

**Comment by Gunner76th** [comment]
https://dl.dropboxusercontent.com/u/251115511/Photos/2015-07-02_19.40.55.png

https://dl.dropboxusercontent.com/u/251115511/Photos/2015-07-02_19.40.58.png

As you can see, the required upgrades are in place, there is energy in the system, but yet there are fully grown sugar cane around it that it is not harvesting.

**Comment by Aroma1997** [comment]
Weird.
