### ISSUE TITLE
Server Crash 1.8- breaking an adjustable chest with a bedrock pickaxe

### ISSUE THREAD

**Issue by ProsperCraft** [Aroma1997/BetterChests#84]
http://pastebin.com/bLrBidaN

**Comment by Aroma1997** [comment]
What mod is the bedrock pickaxe from?

**Comment by UnstableCodeScarlet** [comment]
Judging by his mod list, i would assume the bedrock pick is from the mod "Bedrock Tools" 
Curse Link- http://www.curse.com/mc-mods/minecraft/221330-x-bedrock-tools

Of course that's only a guess, but it's the most likely.

**Comment by Aroma1997** [comment]
1.8 version is discontinued.
