### ISSUE TITLE
1.7.10 Version of Better Chests no Items

### ISSUE THREAD

**Issue by cc778178521** [Aroma1997/BetterChests#89]
Aroma，both Survival mode and Create mode，In addition to a hammer showed no items，even I used the TMI and NEI.
Besides,the recipe disappear too.
My forge version:10.13.4.1614.
I used this mods on 1.7.2 Version,be honest，it gave me a surprise!I'm very love this mods,especially the Player Feeding Upgrade,very very practical,make me try to stop but cannot.
Hope you can fix this problem quickly.

Thanks to this mods to my help.

**Comment by Aroma1997** [comment]
This sounds like BetterChests isn't installed...

**Comment by cc778178521** [comment]
OK，It can work now.
I checked the Jar file,the cause of the error are damaged files.
May be the problem be happen in the carry process.
By the way,I'm from MCBBS found on this mods. 
Because I'm a Chinese... :P
Thanks for your answer,I can happy to play this mods again. :D
