### ISSUE TITLE
1.7.10 - Singleplayer world

### ISSUE THREAD

**Issue by UnDouxTrois** [Aroma1997/BetterChests#91]
In gamemode1 (Creative/Cheat Mode) I place the adjustable Chest on the ground and shortly after, I crash. There is no complete explanation as to why.

VVV Error report.
https://pastebin.com/MXZpEjv7

Edit: Issue is still undetermined, world crashes when I place chest down (As far as I know it is only occurring in gamemode 1) I will test again.

Edit2: Game does NOT crash when reloaded after first crash while chest is still placed, game lags heavily when chest is opened (Adjustable Chest acts as normal single chest when opened and contains same inventory space provided by single chest) and after large spike in lag, crashes.

Edit3: Attempted to open backpack, crashed shortly after attempting to open backpack.

VVV Crash report for my attempt to open the backpack
https://pastebin.com/c6BhijDv

Edit4: Attempted to place Adjustable Chest in Gamemode 0 (Survival Mode) Resulted in crash.

Edit5: Attempted to upgrade Adjustable chest with a space upgrade, despite the current state of the mod for me. Game crashed either due to me upgrading the broken chest, or due to me opening the chest because the space upgrade didn't work to begin with. Either way, it lead to the same outcome. I was in Gamemode0 (Survival Mode) when I attempted this.

Edit6: Interracted with chest, I tried to break the chest with a tinker's construct item called a mattock, it did not work... Game crashed, I get the feeling simply touching the chest (Ie. standing on it or punching it) will crash the game, this mod is unstable, (or the version I had managed to gain is)

This will be the last time I attempt to use this mod, and the last report, thank you for reading. If you'd like to see the file I have, message me in some way.

The mods I am currently using are:

*Aroma1997Core-1.7.10-1.0.2.16
*Better-Chests-Mod-1.7.10
*Carpenter's Blocks v3.3.8.1 - MC 1.7.10
*CoFHCore-[1.7.10]3.1.4-329
*GraveStone-2.12.4
*Mantle-1.7.10-0.3.2b
*OptiFine_1.7.10_HD_U_D8
*TConstruct-1.7.10-1.8.8
*TooManyItems-Mod-Forge-1.7.10
*Xaeros-Minimap-mod-1.7.10

(Gonna have to clear out my crash reports folder after this!) xD

Reply to this informing me if any of these mods are incompatible or if you'd like me to send you the mod's file in some way.

**Comment by Aroma1997** [comment]
The version of BetterChests you're running does not seem to be a official version. It's also horribly outdated. Try to use a version from https://minecraft.curseforge.com/projects/betterchest/files

**Comment by UnDouxTrois** [comment]
Will do, knew I couldn't trust everything on curse forge :/

Thanks!
