### ISSUE TITLE
Looking at Controls in Options causes crash

### ISSUE THREAD

**Issue by DatrixTHLK** [Aroma1997/BetterChests#92]
Hi Aroma1997, 

I was trying to see what the controls were for my game and ended up freezing my game and crashing. After removing this mod I looked into controls and the game no longer freezes.

Minecraft 1.12.2
Forge: 14.23.1.2562
Aroma1997Core: 2.0.0.0.b129
Better Chests: 3.0.0.0.b48

Crash Report: https://gist.github.com/DatrixTHLK/88f73bed46ff1d6ae438beddcc6f4466
FML Log: https://gist.github.com/DatrixTHLK/2e214c27782644b8df96575837f9a5c0

**Comment by Aroma1997** [comment]
Should be working in build 49.

**Comment by DatrixTHLK** [comment]
It does, Thanks.
