### ISSUE TITLE
x.x.b70-72 - Crash on startup + keybind bug

### ISSUE THREAD

**Issue by HellishINC** [Aroma1997/BetterChests#99]
https://gist.github.com/HellishINC/82a23f41d5f6ad192656ebe1dbb1d491

forge-1.12.2-14.23.1.2583-universal.jar
BetterChests-1.12.2-3.0.0.0.b70.jar
Aroma1997Core-1.12.2-2.0.0.0.b135.jar

Does not occur with previous versions.

Also other bug, keybind is reset to "ADD" on every startup. I don't know if it's been fixed since newest version crashes.
 
Edit: Also remembered, when sleeping, the backpack obstructs player vision. Not really an issue inside a safe location but when used with a sleeping bag, this can result in player death as you can't see anything approach you (ie creeper).

**Comment by HellishINC** [comment]
Update: Still an issue with x.71 and x.72. Same error/crash.

**Comment by Aroma1997** [comment]
The keybind bug has been fixed in build 49.  The crash, that appears in your crash log has been fixed in build 73
